### ISSUE TITLE
[FreeBSD] ikev2 subprocess spins after "ikectl reload"

### ISSUE THREAD

**Issue by xcllnt** [xcllnt/openiked#8]
(gdb) bt
#0  0x0000000800873e8d in event_reinit () from /usr/local/lib/libevent-2.0.so.5
#1  0x0000000800876db7 in event_get_callback_arg ()

   from /usr/local/lib/libevent-2.0.so.5
#2  0x0000000800875013 in event_base_loop ()

   from /usr/local/lib/libevent-2.0.so.5
#3  0x00000000004273d5 in proc_run (ps=<value optimized out>, p=0x647150,

```
procs=<value optimized out>, nproc=<value optimized out>, 
run=<value optimized out>, arg=<value optimized out>) at proc.c:439
```
#4  0x00000000004266e9 in proc_init (ps=0x8024181a8,

```
procs=<value optimized out>, nproc=<value optimized out>) at proc.c:120
```
#5  0x000000000040e4a8 in main (argc=<value optimized out>,

```
argv=<value optimized out>) at iked.c:151
```

(gdb) up
#1  0x0000000800876db7 in event_get_callback_arg ()

   from /usr/local/lib/libevent-2.0.so.5
(gdb) up
#2  0x0000000800875013 in event_base_loop ()

   from /usr/local/lib/libevent-2.0.so.5
(gdb) up
#3  0x00000000004273d5 in proc_run (ps=<value optimized out>, p=0x647150,

```
procs=<value optimized out>, nproc=<value optimized out>, 
run=<value optimized out>, arg=<value optimized out>) at proc.c:439
```

439     event_dispatch();
Current language:  auto; currently minimal

**Comment by xcllnt** [comment]
Fixed.
